'use client'
import { LanguageProvider } from "@/components/context/LanguageContext";
import "./globals.css";
import '../styles/app.css'
// import { Next13ProgressBar } from 'next13-progressbar';
// import { useEffect } from "react";

export const metadata = {
  title: "Library Web App",
  description: "Generated by atabeh",
};


export default function RootLayout({ children }) {
  // useEffect(() => {
  //   window.$ = window.jQuery = require('jquery')

  //   $(document).ready(() => {
  //     $('.loading-overlay').removeClass('show')
  //   })
  // }, [])
  return (
    <html lang="ar" dir="rtl">
      <head>
        <link href="/fonts/font-awesome/font-awesome.css" rel="stylesheet" />
        <link href="/fonts/Yekan/regular/fontiran.css" rel="stylesheet" />
        <link href="/fonts/Yekan/fu-num/fontiran.css" rel="stylesheet" />

        <link href="/css/style.css" rel="stylesheet" />
      </head>
      <body>
          {/* <Next13ProgressBar height="4px" color="#DBA100" options={{ showSpinner: true }} showOnShallow /> */}

        <LanguageProvider>
          {children}
        </LanguageProvider>
        {/* <div className="loading-overlay show">
          <div className="spinner"></div>
        </div> */}
      </body>
    </html>
  );
}
